### ISSUE TITLE
闪退 pad

### ISSUE THREAD

**Issue by INTKILOW** [OCNYang/PageTransformerHelp#2]
Process: cn.chuangze.robot.newapp, PID: 12412
    java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4915)
        at android.view.ViewGroup.addView(ViewGroup.java:4746)
        at android.support.v4.view.ViewPager.addView(ViewPager.java:1485)
        at android.view.ViewGroup.addView(ViewGroup.java:4686)
        at android.view.ViewGroup.addView(ViewGroup.java:4659)
        at com.ocnyang.pagetransformerhelp.BannerAdapter.instantiateItem(BannerAdapter.java:82)
        at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1010)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1192)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1092)
        at android.support.v4.view.ViewPager$3.run(ViewPager.java:273)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
    
    
    --------- beginning of system

**Comment by OCNYang** [comment]
这是你上面报错的定位代码：  
https://github.com/OCNYang/PageTransformerHelp/blob/f93a3ef0dff6fd078a89c7d5a84143a1a0f7f016/pagetransformerhelp/src/main/java/com/ocnyang/pagetransformerhelp/BannerAdapter.java#L82

它的上下代码为：  
https://github.com/OCNYang/PageTransformerHelp/blob/f93a3ef0dff6fd078a89c7d5a84143a1a0f7f016/pagetransformerhelp/src/main/java/com/ocnyang/pagetransformerhelp/BannerAdapter.java#L66-L87

这里的 ```container.addView(imageView);``` 可能会有你说的上面错误的可能，可是我测试多次都不能复现它，并且我并没有注意到代码逻辑上有什么疏漏。你能不能更详细的表述下产生上面错误的情景，或说明一下可能造成上面错误的原因和问题所在。

**Comment by INTKILOW** [comment]
轮播图向左滑动没有问题，向右滑动的时候出现这个问题 并且上面的 public void destroyItem(ViewGroup container, int position, Object object) {}没有调用Nexus 5X API 23 6.0代码的话@邮箱@可以发给你，新建的demo

**Comment by OCNYang** [comment]
我运行时向右滑动依然能正常工作；
如果可以的话，可以把你改动的代码复制到下面（改动较少的话）；
如果改动的代码比较多的话，你可以把你的Demo create pull request 。
（如果你对 pull 不熟悉的话，可以参考这篇教程[如何在 Github 上给别人的项目贡献代码](https://www.jianshu.com/p/00cf29d2d66c)）
麻烦了，谢谢！

**Comment by INTKILOW** [comment]
——————————————————————————————————————————   
  implementation 'com.github.OCNYang:PageTransformerHelp:v1.0.0'
    implementation 'com.github.bumptech.glide:glide:4.8.0'
——————————————————————————————————————————
   <com.ocnyang.pagetransformerhelp.BannerViewPager
       android:id="@+id/bannerViewPager"
       android:layout_width="match_parent"
       android:layout_height="144dp"/>


——————————————————————————————————————————

   ArrayList<BannerItemBean> list = new ArrayList<>();

        for(int i =0;i<3;i++) {
            BannerItemBean b = new BannerItemBean();
            b.setImg_path("https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=4053517925,205680591&fm=27&gp=0.jpg");
            b.setTitle(i+"");
            list.add(b);
        }
        BannerViewPager   mBannerViewPager = ((BannerViewPager) findViewById(R.id.bannerViewPager));
        mBannerViewPager
                .setData(list,//set data
                        new ImageLoaderInterface() {
                            @Override
                            public void displayImage(Context context, Object imgPath, ImageView imageView) {
                                //Set your own image loading method according to your needs
                                Glide.with(context).load(imgPath).into(imageView);
                            }
                        })
                .setPageTransformer(new ParallaxTransformer())
                .setAutoPlay(false)
                .setOnBannerItemClickListener(new BannerViewPager.OnBannerItemClickListener() {
                    @Override
                    public void OnClickLister(View view, int currentItem) {

                    }
                })
                .setHaveTitle(true);//set the title show or hide

**Comment by INTKILOW** [comment]
是用的不对吗（BannerViewPager），在我这边闪退 我觉得很奇怪

**Comment by OCNYang** [comment]
这里我已经复现了这个错误，目前发现造成的原因应该是条目的数目小于4造成的，（你可以将条目设置多一点试试）。
同时，我会尽快修复这个错误。

**Comment by INTKILOW** [comment]
mmmm,坑啊是的确实，能加上，上下滚动模式就好了

**Comment by OCNYang** [comment]
这真的是一个很莫名的 bug，而我已经用了一种比较偷懒的方法解决了它。

item 上下滚动模式：你可以试一下 FlipVerticalTransformer ,看看是否是你需要的效果。
